/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedZpravyRouteImport } from './routes/_authenticated/zpravy'
import { Route as AuthenticatedPlatformyRouteImport } from './routes/_authenticated/platformy'
import { Route as AuthenticatedPlanovacRouteImport } from './routes/_authenticated/planovac'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedDesignSystemRouteImport } from './routes/_authenticated/design-system'
import { Route as AuthenticatedApiKliceRouteImport } from './routes/_authenticated/api-klice'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZpravyRoute = AuthenticatedZpravyRouteImport.update({
  id: '/zpravy',
  path: '/zpravy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformyRoute = AuthenticatedPlatformyRouteImport.update({
  id: '/platformy',
  path: '/platformy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanovacRoute = AuthenticatedPlanovacRouteImport.update({
  id: '/planovac',
  path: '/planovac',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignSystemRoute =
  AuthenticatedDesignSystemRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApiKliceRoute = AuthenticatedApiKliceRouteImport.update({
  id: '/api-klice',
  path: '/api-klice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/api-klice': typeof AuthenticatedApiKliceRoute
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/media': typeof AuthenticatedMediaRoute
  '/planovac': typeof AuthenticatedPlanovacRoute
  '/platformy': typeof AuthenticatedPlatformyRoute
  '/zpravy': typeof AuthenticatedZpravyRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/api-klice': typeof AuthenticatedApiKliceRoute
  '/design-system': typeof AuthenticatedDesignSystemRoute
  '/media': typeof AuthenticatedMediaRoute
  '/planovac': typeof AuthenticatedPlanovacRoute
  '/platformy': typeof AuthenticatedPlatformyRoute
  '/zpravy': typeof AuthenticatedZpravyRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/api-klice': typeof AuthenticatedApiKliceRoute
  '/_authenticated/design-system': typeof AuthenticatedDesignSystemRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/planovac': typeof AuthenticatedPlanovacRoute
  '/_authenticated/platformy': typeof AuthenticatedPlatformyRoute
  '/_authenticated/zpravy': typeof AuthenticatedZpravyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api-klice'
    | '/design-system'
    | '/media'
    | '/planovac'
    | '/platformy'
    | '/zpravy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/api-klice'
    | '/design-system'
    | '/media'
    | '/planovac'
    | '/platformy'
    | '/zpravy'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/api-klice'
    | '/_authenticated/design-system'
    | '/_authenticated/media'
    | '/_authenticated/planovac'
    | '/_authenticated/platformy'
    | '/_authenticated/zpravy'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zpravy': {
      id: '/_authenticated/zpravy'
      path: '/zpravy'
      fullPath: '/zpravy'
      preLoaderRoute: typeof AuthenticatedZpravyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platformy': {
      id: '/_authenticated/platformy'
      path: '/platformy'
      fullPath: '/platformy'
      preLoaderRoute: typeof AuthenticatedPlatformyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planovac': {
      id: '/_authenticated/planovac'
      path: '/planovac'
      fullPath: '/planovac'
      preLoaderRoute: typeof AuthenticatedPlanovacRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design-system': {
      id: '/_authenticated/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AuthenticatedDesignSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-klice': {
      id: '/_authenticated/api-klice'
      path: '/api-klice'
      fullPath: '/api-klice'
      preLoaderRoute: typeof AuthenticatedApiKliceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKliceRoute: typeof AuthenticatedApiKliceRoute
  AuthenticatedDesignSystemRoute: typeof AuthenticatedDesignSystemRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedPlanovacRoute: typeof AuthenticatedPlanovacRoute
  AuthenticatedPlatformyRoute: typeof AuthenticatedPlatformyRoute
  AuthenticatedZpravyRoute: typeof AuthenticatedZpravyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKliceRoute: AuthenticatedApiKliceRoute,
  AuthenticatedDesignSystemRoute: AuthenticatedDesignSystemRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedPlanovacRoute: AuthenticatedPlanovacRoute,
  AuthenticatedPlatformyRoute: AuthenticatedPlatformyRoute,
  AuthenticatedZpravyRoute: AuthenticatedZpravyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
